name: tproger_mobile_app
description: Mobile app for tproger.ru
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  html: ^0.15.0
  http: ^0.13.4
  json_annotation: ^4.4.0 
  built_value: ^8.1.4
  built_collection: ^5.1.1 

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  built_value_generator: ^8.1.4 
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - bookmark.png
    - comment.png